"""FlowGuard DevelopmentProcessFlow for generic Research Reasoning Atlas upgrades.

Function block contract:
  PlanScope(Input x State) -> Set(Output x State)
  WriteSkillArtifacts(Input x State) -> Set(Output x State)
  SyncAndValidate(Input x State) -> Set(Output x State)
  CloseWithEvidence(Input x State) -> Set(Output x State)
"""

from __future__ import annotations

from flowguard import (
    PROCESS_ARTIFACT_CODE,
    PROCESS_ARTIFACT_DOC,
    PROCESS_ARTIFACT_MODEL,
    PROCESS_ARTIFACT_REQUIREMENT,
    PROCESS_ARTIFACT_TEST,
    PROCESS_EVIDENCE_PASSED,
    DevelopmentProcessPlan,
    FreshnessRule,
    ProcessAction,
    ProcessArtifact,
    ProcessEvidence,
    ProofArtifactRef,
    ValidationRequirement,
    review_development_process_flow,
)


def proof_artifact(artifact_id: str, command: str, result_path: str, *covered: str) -> ProofArtifactRef:
    return ProofArtifactRef(
        artifact_id,
        producer_route="development_process_flow",
        command=command,
        result_path=result_path,
        result_status=PROCESS_EVIDENCE_PASSED,
        exit_code=0,
        artifact_fingerprints={result_path: "sha256:recorded-by-command-output"},
        covered_obligation_ids=covered,
    )


def current_artifacts(skill_version: str = "1", project_copy_version: str = "1"):
    return (
        ProcessArtifact(
            "requirements.project-plan",
            PROCESS_ARTIFACT_REQUIREMENT,
            "1",
            path="README.md; PLAN.md; docs/*.md",
            owner="project",
            description="User-approved project plan and Guard-family basis.",
        ),
        ProcessArtifact(
            "requirements.openspec",
            PROCESS_ARTIFACT_REQUIREMENT,
            "5",
            path="openspec/changes/add-research-reasoning-atlas",
            owner="openspec",
            upstream_artifact_ids=("requirements.project-plan",),
            description="OpenSpec proposal, design, spec, and task contract for generic Research Reasoning Atlas capability.",
        ),
        ProcessArtifact(
            "model.flowguard-preflight",
            PROCESS_ARTIFACT_MODEL,
            "5",
            path=".flowguard/existing_model_preflight/model.py",
            owner="flowguard",
            upstream_artifact_ids=("requirements.project-plan", "requirements.openspec"),
            description="Existing model ownership route decision including research workflow Atlas orchestration, SourceGuard branch-aware discovery, TraceGuard competing/counterfactual traces, LogicGuard conclusion tournaments, and FlowGuard process boundaries.",
        ),
        ProcessArtifact(
            "model.flowguard-process",
            PROCESS_ARTIFACT_MODEL,
            "5",
            path=".flowguard/development_process_flow/model.py",
            owner="flowguard",
            upstream_artifact_ids=("requirements.openspec",),
            description="Lifecycle freshness model for Atlas implementation, install sync, and closure.",
        ),
        ProcessArtifact(
            "code.installed-skill",
            PROCESS_ARTIFACT_CODE,
            skill_version,
            path="<CODEX_HOME>/skills/research-investigation-workflow",
            owner="skill-creator",
            upstream_artifact_ids=("requirements.openspec", "model.flowguard-preflight"),
            description="Canonical installed Codex research workflow skill.",
        ),
        ProcessArtifact(
            "code.guard-installed-skills",
            PROCESS_ARTIFACT_CODE,
            skill_version,
            path="<CODEX_HOME>/skills/sourceguard; <CODEX_HOME>/skills/traceguard; <CODEX_HOME>/skills/logicguard",
            owner="skill-creator",
            upstream_artifact_ids=("requirements.openspec", "model.flowguard-preflight"),
            description="Installed Guard-family skill files touched by the generic Atlas upgrade.",
        ),
        ProcessArtifact(
            "code.audit-helpers",
            PROCESS_ARTIFACT_CODE,
            skill_version,
            path="<CODEX_HOME>/skills/research-investigation-workflow/scripts",
            owner="skill-creator",
            upstream_artifact_ids=("requirements.openspec",),
            description="Lightweight source marker and source-role coverage audit helpers.",
        ),
        ProcessArtifact(
            "tests.atlas-regression",
            PROCESS_ARTIFACT_TEST,
            "1",
            path="OpenSpec scenarios; generic text checks; multi-domain fixture prompts",
            owner="project",
            description="Generic anti-overfit and multi-domain Atlas regression checks.",
        ),
        ProcessArtifact(
            "doc.project-skill-copy",
            PROCESS_ARTIFACT_DOC,
            project_copy_version,
            path="skills/research-investigation-workflow",
            owner="project",
            upstream_artifact_ids=("code.installed-skill",),
            description="Project-local synchronized copy for review.",
        ),
        ProcessArtifact(
            "tests.skill-validator",
            PROCESS_ARTIFACT_TEST,
            "1",
            path="<CODEX_HOME>/skills/.system/skill-creator/scripts/quick_validate.py",
            owner="skill-creator",
            description="Skill metadata validator.",
        ),
    )


def implementation_plan() -> DevelopmentProcessPlan:
    return DevelopmentProcessPlan(
        "research-reasoning-atlas-skill-lifecycle",
        require_proof_artifacts=True,
        artifacts=current_artifacts(skill_version="5", project_copy_version="5"),
        actions=(
            ProcessAction(
                "kb-and-command-preflight",
                reads_artifacts=("requirements.project-plan",),
                produced_evidence_ids=("preflight-evidence",),
                description="Predictive KB, skill-creator, command-surface, git, and coordination checks.",
            ),
            ProcessAction(
                "write-openspec-contract",
                reads_artifacts=("requirements.project-plan",),
                writes_artifacts=("requirements.openspec",),
                order_after=("kb-and-command-preflight",),
            ),
            ProcessAction(
                "write-flowguard-models",
                reads_artifacts=("requirements.openspec",),
                writes_artifacts=("model.flowguard-preflight", "model.flowguard-process"),
                produced_evidence_ids=("flowguard-preflight-pass",),
                order_after=("write-openspec-contract",),
            ),
            ProcessAction(
                "write-installed-skill",
                reads_artifacts=("requirements.openspec", "model.flowguard-preflight"),
                writes_artifacts=("code.installed-skill", "code.guard-installed-skills", "code.audit-helpers"),
                invalidates_evidence=("skill-validate-pass", "smoke-review-pass", "sync-hash-pass"),
                order_after=("write-flowguard-models",),
            ),
            ProcessAction(
                "sync-project-copy",
                reads_artifacts=("code.installed-skill", "code.guard-installed-skills", "code.audit-helpers"),
                writes_artifacts=("doc.project-skill-copy",),
                produced_evidence_ids=("sync-hash-pass",),
                order_after=("write-installed-skill",),
            ),
            ProcessAction(
                "run-validation",
                reads_artifacts=("code.installed-skill", "code.guard-installed-skills", "code.audit-helpers", "doc.project-skill-copy", "tests.skill-validator", "tests.atlas-regression"),
                produced_evidence_ids=("skill-validate-pass", "smoke-review-pass", "openspec-validate-pass", "helper-smoke-pass", "atlas-regression-pass", "anti-overfit-pass"),
                order_after=("sync-project-copy",),
            ),
            ProcessAction(
                "claim-done",
                action_type="claim_done",
                required_validation_ids=(
                    "preflight-current",
                    "flowguard-current",
                    "skill-validator-current",
                    "sync-current",
                    "smoke-review-current",
                    "openspec-current",
                    "helper-smoke-current",
                    "atlas-regression-current",
                    "anti-overfit-current",
                ),
                order_after=("run-validation",),
            ),
        ),
        evidence=(
            ProcessEvidence(
                "preflight-evidence",
                evidence_kind="preflight",
                producer_route="predictive_kb_preflight",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("requirements.project-plan",),
                covered_versions={"requirements.project-plan": "1"},
                validation_requirement_ids=("preflight-current",),
                produced_by_action_id="kb-and-command-preflight",
                command="KB search plus command-surface checks",
                proof_artifact=proof_artifact(
                    "artifact:preflight-evidence",
                    "KB search plus command-surface checks",
                    "console:preflight",
                    "preflight-current",
                ),
            ),
            ProcessEvidence(
                "flowguard-preflight-pass",
                evidence_kind="flowguard",
                producer_route="existing_model_preflight",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("model.flowguard-preflight", "model.flowguard-process"),
                covered_versions={"model.flowguard-preflight": "5", "model.flowguard-process": "5"},
                validation_requirement_ids=("flowguard-current",),
                produced_by_action_id="write-flowguard-models",
                command="python .flowguard/existing_model_preflight/run_checks.py; python .flowguard/development_process_flow/run_checks.py",
                proof_artifact=proof_artifact(
                    "artifact:flowguard-preflight-pass",
                    "python .flowguard/existing_model_preflight/run_checks.py; python .flowguard/development_process_flow/run_checks.py",
                    "console:flowguard-checks",
                    "flowguard-current",
                ),
            ),
            ProcessEvidence(
                "skill-validate-pass",
                evidence_kind="skill_validation",
                producer_route="skill_creator",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.installed-skill",),
                verifier_artifacts=("tests.skill-validator",),
                covered_versions={"code.installed-skill": "5", "tests.skill-validator": "1"},
                validation_requirement_ids=("skill-validator-current",),
                produced_by_action_id="run-validation",
                command="python <CODEX_HOME>/skills/.system/skill-creator/scripts/quick_validate.py <CODEX_HOME>/skills/research-investigation-workflow",
                proof_artifact=proof_artifact(
                    "artifact:skill-validate-pass",
                    "quick_validate.py installed skill",
                    "console:quick-validate",
                    "skill-validator-current",
                ),
            ),
            ProcessEvidence(
                "sync-hash-pass",
                evidence_kind="sync_hash",
                producer_route="development_process_flow",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.installed-skill", "code.guard-installed-skills", "code.audit-helpers", "doc.project-skill-copy"),
                covered_versions={"code.installed-skill": "5", "code.guard-installed-skills": "5", "code.audit-helpers": "5", "doc.project-skill-copy": "5"},
                validation_requirement_ids=("sync-current",),
                produced_by_action_id="sync-project-copy",
                command="Compare installed and project skill file hashes",
                proof_artifact=proof_artifact(
                    "artifact:sync-hash-pass",
                    "Compare installed and project skill file hashes",
                    "console:sync-hash",
                    "sync-current",
                ),
            ),
            ProcessEvidence(
                "smoke-review-pass",
                evidence_kind="manual_smoke_review",
                producer_route="skill_creator",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.installed-skill",),
                covered_versions={"code.installed-skill": "5"},
                validation_requirement_ids=("smoke-review-current",),
                produced_by_action_id="run-validation",
                command="Manual acceptance criteria smoke review",
                proof_artifact=proof_artifact(
                    "artifact:smoke-review-pass",
                    "Manual acceptance criteria smoke review",
                    "console:smoke-review",
                    "smoke-review-current",
                ),
            ),
            ProcessEvidence(
                "openspec-validate-pass",
                evidence_kind="openspec_validation",
                producer_route="openspec",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("requirements.openspec",),
                covered_versions={"requirements.openspec": "5"},
                validation_requirement_ids=("openspec-current",),
                produced_by_action_id="run-validation",
                command="openspec validate add-research-reasoning-atlas --strict",
                proof_artifact=proof_artifact(
                    "artifact:openspec-validate-pass",
                    "openspec validate add-research-reasoning-atlas --strict",
                    "console:openspec-validate",
                    "openspec-current",
                ),
            ),
            ProcessEvidence(
                "helper-smoke-pass",
                evidence_kind="helper_smoke",
                producer_route="development_process_flow",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.audit-helpers",),
                covered_versions={"code.audit-helpers": "5"},
                validation_requirement_ids=("helper-smoke-current",),
                produced_by_action_id="run-validation",
                command="Run known-good and known-bad Markdown audit helper fixtures",
                proof_artifact=proof_artifact(
                    "artifact:helper-smoke-pass",
                    "Run known-good and known-bad Markdown audit helper fixtures",
                    "console:helper-smoke",
                    "helper-smoke-current",
                ),
            ),
            ProcessEvidence(
                "atlas-regression-pass",
                evidence_kind="atlas_regression",
                producer_route="development_process_flow",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.installed-skill", "code.guard-installed-skills", "tests.atlas-regression"),
                covered_versions={"code.installed-skill": "5", "code.guard-installed-skills": "5", "tests.atlas-regression": "1"},
                validation_requirement_ids=("atlas-regression-current",),
                produced_by_action_id="run-validation",
                command="Run generic Atlas fixture checks across unrelated topic classes",
                proof_artifact=proof_artifact(
                    "artifact:atlas-regression-pass",
                    "Run generic Atlas fixture checks across unrelated topic classes",
                    "console:atlas-regression",
                    "atlas-regression-current",
                ),
            ),
            ProcessEvidence(
                "anti-overfit-pass",
                evidence_kind="anti_overfit_text_check",
                producer_route="development_process_flow",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.installed-skill", "code.guard-installed-skills"),
                covered_versions={"code.installed-skill": "5", "code.guard-installed-skills": "5"},
                validation_requirement_ids=("anti-overfit-current",),
                produced_by_action_id="run-validation",
                command="Run text checks for prohibited domain-specific checklist terms in core skill guidance",
                proof_artifact=proof_artifact(
                    "artifact:anti-overfit-pass",
                    "Run text checks for prohibited domain-specific checklist terms in core skill guidance",
                    "console:anti-overfit",
                    "anti-overfit-current",
                ),
            ),
        ),
        validation_requirements=(
            ValidationRequirement(
                "preflight-current",
                required_artifact_ids=("requirements.project-plan",),
                required_evidence_kinds=("preflight",),
                v_model_pair=True,
                command="Run KB and command-surface preflight.",
            ),
            ValidationRequirement(
                "flowguard-current",
                required_artifact_ids=("model.flowguard-preflight", "model.flowguard-process"),
                required_evidence_kinds=("flowguard",),
                v_model_pair=True,
                command="python .flowguard/existing_model_preflight/run_checks.py; python .flowguard/development_process_flow/run_checks.py",
            ),
            ValidationRequirement(
                "skill-validator-current",
                required_artifact_ids=("code.installed-skill",),
                required_evidence_kinds=("skill_validation",),
                v_model_pair=True,
                command="quick_validate.py installed skill",
            ),
            ValidationRequirement(
                "sync-current",
                required_artifact_ids=("code.installed-skill", "code.guard-installed-skills", "code.audit-helpers", "doc.project-skill-copy"),
                required_evidence_kinds=("sync_hash",),
                v_model_pair=True,
                command="Compare installed and project skill file hashes.",
            ),
            ValidationRequirement(
                "smoke-review-current",
                required_artifact_ids=("code.installed-skill",),
                required_evidence_kinds=("manual_smoke_review",),
                v_model_pair=True,
                command="Manual acceptance criteria smoke review.",
            ),
            ValidationRequirement(
                "openspec-current",
                required_artifact_ids=("requirements.openspec",),
                required_evidence_kinds=("openspec_validation",),
                v_model_pair=True,
                command="openspec validate add-research-reasoning-atlas --strict",
            ),
            ValidationRequirement(
                "helper-smoke-current",
                required_artifact_ids=("code.audit-helpers",),
                required_evidence_kinds=("helper_smoke",),
                v_model_pair=True,
                command="Run helper smoke tests on known-good and known-bad Markdown fixtures.",
            ),
            ValidationRequirement(
                "atlas-regression-current",
                required_artifact_ids=("code.installed-skill", "code.guard-installed-skills", "tests.atlas-regression"),
                required_evidence_kinds=("atlas_regression",),
                v_model_pair=True,
                command="Run generic Atlas fixture checks across unrelated topic classes.",
            ),
            ValidationRequirement(
                "anti-overfit-current",
                required_artifact_ids=("code.installed-skill", "code.guard-installed-skills"),
                required_evidence_kinds=("anti_overfit_text_check",),
                v_model_pair=True,
                command="Run text checks for prohibited domain-specific checklist terms in core skill guidance.",
            ),
        ),
        freshness_rules=(
            FreshnessRule(
                "project-plan-invalidates-openspec-and-models",
                upstream_artifact_id="requirements.project-plan",
                invalidates_artifact_ids=(
                    "requirements.openspec",
                    "model.flowguard-preflight",
                    "model.flowguard-process",
                    "code.installed-skill",
                    "code.guard-installed-skills",
                    "code.audit-helpers",
                    "doc.project-skill-copy",
                    "tests.atlas-regression",
                ),
                invalidates_evidence_kinds=(
                    "preflight",
                    "flowguard",
                    "skill_validation",
                    "manual_smoke_review",
                    "sync_hash",
                    "openspec_validation",
                ),
            ),
            FreshnessRule(
                "openspec-invalidates-skill-validation",
                upstream_artifact_id="requirements.openspec",
                invalidates_artifact_ids=(
                    "model.flowguard-preflight",
                    "model.flowguard-process",
                    "code.installed-skill",
                    "code.guard-installed-skills",
                    "code.audit-helpers",
                    "doc.project-skill-copy",
                ),
                invalidates_evidence_kinds=("flowguard", "skill_validation", "manual_smoke_review", "sync_hash", "helper_smoke", "atlas_regression", "anti_overfit_text_check"),
            ),
            FreshnessRule(
                "existing-preflight-invalidates-skill-boundary",
                upstream_artifact_id="model.flowguard-preflight",
                invalidates_artifact_ids=("code.installed-skill", "code.guard-installed-skills", "code.audit-helpers", "doc.project-skill-copy"),
                invalidates_evidence_kinds=("flowguard", "skill_validation", "manual_smoke_review", "sync_hash", "helper_smoke", "atlas_regression", "anti_overfit_text_check"),
            ),
            FreshnessRule(
                "installed-skill-invalidates-sync-and-smoke",
                upstream_artifact_id="code.installed-skill",
                invalidates_artifact_ids=("doc.project-skill-copy",),
                invalidates_evidence_kinds=("sync_hash", "manual_smoke_review", "skill_validation"),
            ),
            FreshnessRule(
                "audit-helpers-invalidate-helper-smoke",
                upstream_artifact_id="code.audit-helpers",
                invalidates_evidence_kinds=("helper_smoke", "sync_hash", "atlas_regression", "anti_overfit_text_check"),
            ),
            FreshnessRule(
                "flowguard-model-invalidates-closure",
                upstream_artifact_id="model.flowguard-process",
                invalidates_evidence_kinds=("flowguard",),
            ),
        ),
    )


def broken_stale_plan() -> DevelopmentProcessPlan:
    return DevelopmentProcessPlan(
        "research-investigation-workflow-stale-lifecycle",
        artifacts=current_artifacts(skill_version="2", project_copy_version="1"),
        actions=(
            ProcessAction("run-validation-too-early", produced_evidence_ids=("skill-validate-pass",)),
            ProcessAction("edit-installed-skill-after-validation", writes_artifacts=("code.installed-skill",)),
            ProcessAction("claim-done", action_type="claim_done", required_evidence_ids=("skill-validate-pass",)),
        ),
        evidence=(
            ProcessEvidence(
                "skill-validate-pass",
                evidence_kind="skill_validation",
                producer_route="skill_creator",
                status=PROCESS_EVIDENCE_PASSED,
                covers_artifacts=("code.installed-skill",),
                verifier_artifacts=("tests.skill-validator",),
                covered_versions={"code.installed-skill": "1", "tests.skill-validator": "1"},
                validation_requirement_ids=("skill-validator-current",),
                produced_by_action_id="run-validation-too-early",
                command="quick_validate.py installed skill",
            ),
        ),
        validation_requirements=(
            ValidationRequirement(
                "skill-validator-current",
                required_artifact_ids=("code.installed-skill",),
                required_evidence_kinds=("skill_validation",),
                evidence_ids=("skill-validate-pass",),
                v_model_pair=True,
                command="quick_validate.py installed skill",
            ),
        ),
        freshness_rules=(
            FreshnessRule(
                "installed-skill-invalidates-validation",
                upstream_artifact_id="code.installed-skill",
                invalidates_evidence_kinds=("skill_validation",),
            ),
        ),
    )


def run_checks():
    return review_development_process_flow(implementation_plan()), review_development_process_flow(broken_stale_plan())
